Fix missing migration in dev docker app creation
We need to make sure assemblies is used. Otherwise we get the following
error:

```
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable:
ERROR:  relation "decidim_assemblies" does not exist
```